spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: hzx2001
    hikari: #数据库连接池
      pool-name: Hzx_Hikari_Poll  #连接池的名称
      # 最小的空闲连接数目
      minimum-idle: 5
      #空闲连接的最大存活时间，默认是 60000
      idle-timeout: 60000
      # 最大连接数目
      maximum-pool-size: 10
      # 从连接池返回来的连接自动提交
      auto-commit: true
      # 连接最大的存活时间，0表示永久存活，默认是 180000 (30 分钟)
      max-lifetime: 180000
      # 连接超时时间，默认是 30000 秒
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: select 1
  #mybatis-plus 配置
  # 配置 redis
  redis:
    host: 192.168.23.128
    port: 6379
    password: hzx2001
    database: 0 #配置默认访问的数据库
    connect-timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数目: 默认是 8
        max-active: 28
        # 最大连接阻塞等待时间，默认是 -1
        max-wait: 10000ms
        # 最大空闲连接，默认是 8
        max-idle: 200
        # 最小空闲连接，默认是 0
        min-idle: 5
  rabbitmq:
    host: 192.168.23.128
    username: guest   # 登录用户名和密码默认 guest
    password: guest
    virtual-host: / #虚拟主机
    port: 5672    #端口
    listener:
      simple:
        concurrency: 10           # 消费者的最小数量
        max-concurrency: 10       # 消费者的最大数量
        prefetch: 1               # 限制消费者，每次只能处理一条消息，处理完才能继续下一条处理
        auto-startup: true        # 启动时是否默认启动容器，默认为 true
        default-requeue-rejected: true #被拒绝时重新进入队列
    template:
      retry:
        enabled: true             #启用消息重试机制，默认为 false
        initial-interval: 1000ms  #初始重试间隔时间
        max-attempts: 3           #重试最大次数，默认为 3 次
        max-interval: 10000ms     #重试的间隔乘数
        multiplier: 1             #配置 2 的话，第一次等 1s, 第二次等 2s,第三次等 4s
mybatis-plus:
  #配置 mybatis 数据返回类型别名
  type-aliases-package: com.hzx.seckill.pojo
  #配置 mapper.xml 映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
#mybatis sql 打印
logging:
  level:
    com.hzx.seckill.mapper: debug
